### PR TITLE
Preserve commit history of all Mercurial repositories.

### PR DESCRIPTION
**Pull request by nsoranzo**
This needs git-remote-hg https://github.com/felipec/git-remote-hg .

It is still running on my workstation, but seems to work!

### CODE REVIEW

**Comment by nsoranzo** [comment]
It worked flawlessly, the result is this repo: https://github.com/nsoranzo/devteamtest4 .

**Comment by jmchilton** [comment]
Thanks a bunch!

**Comment by jmchilton** [comment]
Nicola - I assumed you cared because you had a bunch of commits with your name on them but it doesn't look like it https://github.com/nsoranzo/devteamtest4/graphs/contributors :), how altruistic of you!

**Comment by nsoranzo** [comment]
I don't have commit access to any of these Tool Shed repos, I could only contribute with bug reports or patches which have not been attributed most of the times.

Anyway I always think there is value in preserving histories, it was me who saved ncbi_blast_plus's history when moved from galaxy-central to github.

**Pull request merged**
